// GENERATED by ios/scripts/make-treble-clef.py. Do not edit by hand.
//
// Source artwork: svgrepo.com/svg/98269/treble-clef, kept at
// ios/scripts/treble-clef.svg so this can be regenerated with no network.
// index.html draws the same two paths with the same placement.
//
// The clef is drawn rather than set as U+1D11E because no font in the iOS
// runtime has that codepoint: 0 of 264 checked. It is FILLED, not stroked.
//
// Placement, measured rather than eyeballed: the source glyph is 276.164 units
// square with its spiral centred at (148, 172). A G clef is only a G clef if that
// spiral sits on the G4 line, which this staff draws at y = 120, so the glyph is
// scaled to 135 units tall (6.75 staff spaces) and translated to put the spiral
// there. scale 0.48884, translate (-9.24, 35.92).

import SwiftUI

enum TrebleClef {
    static let path: Path = {
        var p = Path()
        // subpath 1 of 2
        p.move(to: CGPoint(x: 67.37, y: 65.97))
        p.addCurve(to: CGPoint(x: 60.42, y: 73.60), control1: CGPoint(x: 65.36, y: 69.04), control2: CGPoint(x: 63.03, y: 71.60))
        p.addLine(to: CGPoint(x: 56.16, y: 77.01))
        p.addCurve(to: CGPoint(x: 42.20, y: 90.92), control1: CGPoint(x: 49.64, y: 82.80), control2: CGPoint(x: 44.94, y: 87.48))
        p.addCurve(to: CGPoint(x: 34.07, y: 109.79), control1: CGPoint(x: 37.21, y: 97.17), control2: CGPoint(x: 34.48, y: 103.52))
        p.addCurve(to: CGPoint(x: 40.07, y: 129.76), control1: CGPoint(x: 33.61, y: 116.87), control2: CGPoint(x: 35.62, y: 123.59))
        p.addCurve(to: CGPoint(x: 57.74, y: 140.36), control1: CGPoint(x: 44.78, y: 136.34), control2: CGPoint(x: 50.72, y: 139.90))
        p.addCurve(to: CGPoint(x: 62.58, y: 140.35), control1: CGPoint(x: 59.35, y: 140.47), control2: CGPoint(x: 61.12, y: 140.45))
        p.addLine(to: CGPoint(x: 62.03, y: 135.42))
        p.addCurve(to: CGPoint(x: 58.79, y: 135.45), control1: CGPoint(x: 61.01, y: 135.51), control2: CGPoint(x: 59.93, y: 135.52))
        p.addCurve(to: CGPoint(x: 46.54, y: 129.79), control1: CGPoint(x: 54.18, y: 135.15), control2: CGPoint(x: 50.06, y: 133.24))
        p.addCurve(to: CGPoint(x: 41.51, y: 117.72), control1: CGPoint(x: 42.86, y: 126.21), control2: CGPoint(x: 41.22, y: 122.26))
        p.addCurve(to: CGPoint(x: 58.10, y: 92.40), control1: CGPoint(x: 42.07, y: 109.12), control2: CGPoint(x: 47.65, y: 100.61))
        p.addLine(to: CGPoint(x: 62.76, y: 88.68))
        p.addCurve(to: CGPoint(x: 72.64, y: 75.57), control1: CGPoint(x: 66.87, y: 85.18), control2: CGPoint(x: 70.19, y: 80.77))
        p.addCurve(to: CGPoint(x: 76.88, y: 58.97), control1: CGPoint(x: 75.07, y: 70.41), control2: CGPoint(x: 76.50, y: 64.83))
        p.addCurve(to: CGPoint(x: 75.48, y: 46.28), control1: CGPoint(x: 77.11, y: 55.53), control2: CGPoint(x: 76.63, y: 51.26))
        p.addCurve(to: CGPoint(x: 68.57, y: 35.92), control1: CGPoint(x: 73.89, y: 39.51), control2: CGPoint(x: 71.64, y: 36.13))
        p.addCurve(to: CGPoint(x: 64.83, y: 37.69), control1: CGPoint(x: 67.48, y: 35.86), control2: CGPoint(x: 66.28, y: 36.41))
        p.addCurve(to: CGPoint(x: 57.16, y: 49.20), control1: CGPoint(x: 61.28, y: 40.89), control2: CGPoint(x: 58.70, y: 44.77))
        p.addCurve(to: CGPoint(x: 54.81, y: 62.66), control1: CGPoint(x: 55.97, y: 52.59), control2: CGPoint(x: 55.18, y: 57.11))
        p.addCurve(to: CGPoint(x: 55.69, y: 74.37), control1: CGPoint(x: 54.66, y: 64.97), control2: CGPoint(x: 54.96, y: 69.23))
        p.addLine(to: CGPoint(x: 60.02, y: 70.37))
        p.addCurve(to: CGPoint(x: 60.06, y: 68.56), control1: CGPoint(x: 60.00, y: 69.79), control2: CGPoint(x: 60.02, y: 69.19))
        p.addCurve(to: CGPoint(x: 62.70, y: 57.17), control1: CGPoint(x: 60.29, y: 65.03), control2: CGPoint(x: 61.18, y: 61.19))
        p.addCurve(to: CGPoint(x: 67.65, y: 50.23), control1: CGPoint(x: 64.63, y: 52.14), control2: CGPoint(x: 66.46, y: 50.62))
        p.addCurve(to: CGPoint(x: 68.64, y: 50.10), control1: CGPoint(x: 67.98, y: 50.12), control2: CGPoint(x: 68.30, y: 50.08))
        p.addCurve(to: CGPoint(x: 71.48, y: 54.98), control1: CGPoint(x: 70.19, y: 50.21), control2: CGPoint(x: 71.75, y: 50.86))
        p.addCurve(to: CGPoint(x: 67.37, y: 65.97), control1: CGPoint(x: 71.26, y: 58.47), control2: CGPoint(x: 69.87, y: 62.17))
        p.closeSubpath()
        // subpath 2 of 2
        p.move(to: CGPoint(x: 71.20, y: 138.17))
        p.addCurve(to: CGPoint(x: 78.33, y: 132.47), control1: CGPoint(x: 74.00, y: 136.91), control2: CGPoint(x: 76.39, y: 135.00))
        p.addCurve(to: CGPoint(x: 82.47, y: 121.20), control1: CGPoint(x: 80.80, y: 129.26), control2: CGPoint(x: 82.19, y: 125.47))
        p.addCurve(to: CGPoint(x: 78.74, y: 107.08), control1: CGPoint(x: 82.82, y: 115.96), control2: CGPoint(x: 81.56, y: 111.21))
        p.addCurve(to: CGPoint(x: 66.16, y: 99.73), control1: CGPoint(x: 75.65, y: 102.55), control2: CGPoint(x: 71.42, y: 100.08))
        p.addCurve(to: CGPoint(x: 64.25, y: 99.75), control1: CGPoint(x: 65.55, y: 99.69), control2: CGPoint(x: 64.91, y: 99.70))
        p.addLine(to: CGPoint(x: 63.13, y: 91.34))
        p.addLine(to: CGPoint(x: 58.40, y: 94.82))
        p.addLine(to: CGPoint(x: 59.12, y: 100.78))
        p.addCurve(to: CGPoint(x: 51.78, y: 106.28), control1: CGPoint(x: 56.30, y: 101.95), control2: CGPoint(x: 53.83, y: 103.80))
        p.addCurve(to: CGPoint(x: 47.89, y: 115.76), control1: CGPoint(x: 49.43, y: 109.18), control2: CGPoint(x: 48.11, y: 112.36))
        p.addCurve(to: CGPoint(x: 50.23, y: 125.33), control1: CGPoint(x: 47.66, y: 119.28), control2: CGPoint(x: 48.45, y: 122.51))
        p.addCurve(to: CGPoint(x: 53.89, y: 129.27), control1: CGPoint(x: 51.15, y: 126.84), control2: CGPoint(x: 52.43, y: 128.17))
        p.addCurve(to: CGPoint(x: 59.50, y: 129.95), control1: CGPoint(x: 56.29, y: 131.05), control2: CGPoint(x: 59.06, y: 130.92))
        p.addCurve(to: CGPoint(x: 57.01, y: 125.43), control1: CGPoint(x: 59.94, y: 128.98), control2: CGPoint(x: 58.30, y: 127.46))
        p.addCurve(to: CGPoint(x: 55.91, y: 121.27), control1: CGPoint(x: 56.27, y: 124.28), control2: CGPoint(x: 55.91, y: 122.90))
        p.addCurve(to: CGPoint(x: 60.95, y: 113.55), control1: CGPoint(x: 55.91, y: 117.83), control2: CGPoint(x: 57.99, y: 114.86))
        p.addLine(to: CGPoint(x: 63.73, y: 135.16))
        p.addLine(to: CGPoint(x: 64.38, y: 140.18))
        p.addCurve(to: CGPoint(x: 65.62, y: 147.28), control1: CGPoint(x: 64.80, y: 142.56), control2: CGPoint(x: 65.22, y: 144.93))
        p.addCurve(to: CGPoint(x: 66.12, y: 155.45), control1: CGPoint(x: 66.10, y: 150.45), control2: CGPoint(x: 66.28, y: 153.20))
        p.addCurve(to: CGPoint(x: 63.23, y: 163.02), control1: CGPoint(x: 65.92, y: 158.56), control2: CGPoint(x: 64.95, y: 161.11))
        p.addCurve(to: CGPoint(x: 59.42, y: 165.43), control1: CGPoint(x: 62.14, y: 164.24), control2: CGPoint(x: 60.86, y: 165.00))
        p.addCurve(to: CGPoint(x: 62.56, y: 157.86), control1: CGPoint(x: 61.36, y: 163.49), control2: CGPoint(x: 62.56, y: 160.82))
        p.addCurve(to: CGPoint(x: 51.87, y: 147.17), control1: CGPoint(x: 62.56, y: 151.96), control2: CGPoint(x: 57.77, y: 147.17))
        p.addCurve(to: CGPoint(x: 47.30, y: 148.23), control1: CGPoint(x: 50.23, y: 147.17), control2: CGPoint(x: 48.69, y: 147.57))
        p.addCurve(to: CGPoint(x: 46.79, y: 148.51), control1: CGPoint(x: 47.13, y: 148.30), control2: CGPoint(x: 46.96, y: 148.42))
        p.addCurve(to: CGPoint(x: 45.67, y: 149.17), control1: CGPoint(x: 46.41, y: 148.71), control2: CGPoint(x: 46.03, y: 148.92))
        p.addCurve(to: CGPoint(x: 45.31, y: 149.47), control1: CGPoint(x: 45.55, y: 149.26), control2: CGPoint(x: 45.43, y: 149.37))
        p.addCurve(to: CGPoint(x: 41.22, y: 157.40), control1: CGPoint(x: 42.92, y: 151.33), control2: CGPoint(x: 41.36, y: 154.17))
        p.addCurve(to: CGPoint(x: 41.21, y: 157.42), control1: CGPoint(x: 41.22, y: 157.41), control2: CGPoint(x: 41.21, y: 157.41))
        p.addCurve(to: CGPoint(x: 41.21, y: 157.42), control1: CGPoint(x: 41.21, y: 157.42), control2: CGPoint(x: 41.21, y: 157.42))
        p.addCurve(to: CGPoint(x: 41.17, y: 157.86), control1: CGPoint(x: 41.21, y: 157.58), control2: CGPoint(x: 41.17, y: 157.71))
        p.addCurve(to: CGPoint(x: 41.21, y: 158.22), control1: CGPoint(x: 41.17, y: 157.99), control2: CGPoint(x: 41.20, y: 158.10))
        p.addCurve(to: CGPoint(x: 45.53, y: 167.08), control1: CGPoint(x: 41.20, y: 161.69), control2: CGPoint(x: 42.64, y: 164.67))
        p.addCurve(to: CGPoint(x: 55.25, y: 170.88), control1: CGPoint(x: 48.26, y: 169.36), control2: CGPoint(x: 51.53, y: 170.64))
        p.addCurve(to: CGPoint(x: 61.32, y: 170.16), control1: CGPoint(x: 57.37, y: 171.02), control2: CGPoint(x: 59.41, y: 170.78))
        p.addCurve(to: CGPoint(x: 65.79, y: 167.87), control1: CGPoint(x: 62.88, y: 169.65), control2: CGPoint(x: 64.39, y: 168.88))
        p.addCurve(to: CGPoint(x: 71.30, y: 158.32), control1: CGPoint(x: 69.19, y: 165.41), control2: CGPoint(x: 71.05, y: 162.20))
        p.addCurve(to: CGPoint(x: 70.84, y: 147.85), control1: CGPoint(x: 71.50, y: 155.35), control2: CGPoint(x: 71.35, y: 151.85))
        p.addLine(to: CGPoint(x: 69.46, y: 138.84))
        p.addLine(to: CGPoint(x: 65.96, y: 112.98))
        p.addCurve(to: CGPoint(x: 72.81, y: 121.28), control1: CGPoint(x: 69.86, y: 113.73), control2: CGPoint(x: 72.81, y: 117.16))
        p.addCurve(to: CGPoint(x: 70.10, y: 131.24), control1: CGPoint(x: 72.81, y: 124.20), control2: CGPoint(x: 71.87, y: 128.82))
        p.addLine(to: CGPoint(x: 71.20, y: 138.17))
        p.closeSubpath()
        return p
    }()
}
